/* Generated By:JavaCC: Do not edit this line. jmmConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface jmmConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 3;
  /** RegularExpression Id. */
  int IF = 4;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int NEW = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int TRUE = 9;
  /** RegularExpression Id. */
  int MAIN = 10;
  /** RegularExpression Id. */
  int THIS = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int PUBLIC = 15;
  /** RegularExpression Id. */
  int STATIC = 16;
  /** RegularExpression Id. */
  int STRING = 17;
  /** RegularExpression Id. */
  int LENGTH = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int IMPORT = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int EXTENDS = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "<INTEGERLITERAL>",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"void\"",
    "\"else\"",
    "\"true\"",
    "\"main\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"length\"",
    "\"return\"",
    "\"import\"",
    "\"boolean\"",
    "\"extends\"",
    "<IDENTIFIER>",
    "\".\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"!\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
