/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.1_2 */
public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTPROGRAM = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTIMPORTMATERIAL = 3;
  public int JJTCLASS = 4;
  public int JJTEXTENDEDCLASSNAME = 6;
  public int JJTVARDECLARATION = 7;
  public int JJTVARTYPE = 8;
  public int JJTVARNAME = 9;
  public int JJTNORMALMETHODDECLARATION = 10;
  public int JJTRETURNTYPE = 11;
  public int JJTMETHODNAME = 12;
  public int JJTRETURNVALUE = 13;
  public int JJTMAINMETHODDECLARATION = 14;
  public int JJTCLARGSNAME = 15;
  public int JJTMETHODDECLARATIONARGS = 16;
  public int JJTPARAMETERTYPE = 17;
  public int JJTPARAMETERNAME = 18;
  public int JJTPARAMETER = 19;
  public int JJTBODY = 20;
  public int JJTIF = 21;
  public int JJTELSE = 22;
  public int JJTWHILE = 23;
  public int JJTASSIGNRECIPIENT = 24;
  public int JJTASSIGN = 25;
  public int JJTARRAYINDEX = 26;
  public int JJTARRAYASSIGN = 27;
  public int JJTINTEGERLITERAL = 28;
  public int JJTTRUE = 29;
  public int JJTFALSE = 30;
  public int JJTVARIABLENAME = 31;
  public int JJTTHIS = 32;
  public int JJTNEGATION = 33;
  public int JJTNEW = 34;
  public int JJTARRAYINITIALIZER = 35;
  public int JJTCONSTRUCTORCALL = 36;
  public int JJTNEWOBJECTCLASSNAME = 37;
  public int JJTLENGTH = 38;
  public int JJTMETHODCALL = 39;
  public int JJTATTRIBUTECALL = 40;
  public int JJTMETHODCALLARGS = 41;
  public int JJTAND = 42;
  public int JJTSMALLERTHAN = 43;
  public int JJTADDITION = 44;
  public int JJTSUBTRACTION = 45;
  public int JJTMULTIPLICATION = 46;
  public int JJTDIVISION = 47;
  public int JJTERROR = 48;

  public String[] jjtNodeName = {
    "void",
    "Program",
    "ImportDeclaration",
    "ImportMaterial",
    "Class",
    "ExtendedClassName",
    "VarDeclaration",
    "VarType",
    "VarName",
    "NormalMethodDeclaration",
    "ReturnType",
    "MethodName",
    "ReturnValue",
    "MainMethodDeclaration",
    "ClArgsName",
    "MethodDeclarationArgs",
    "ParameterType",
    "ParameterName",
    "Parameter",
    "Body",
    "If",
    "Else",
    "While",
    "AssignRecipient",
    "Assign",
    "ArrayIndex",
    "ArrayAssign",
    "IntegerLiteral",
    "True",
    "False",
    "VariableName",
    "This",
    "Negation",
    "New",
    "ArrayInitializer",
    "ConstructorCall",
    "NewObjectClassName",
    "Length",
    "MethodCall",
    "AttributeCall",
    "MethodCallArgs",
    "And",
    "SmallerThan",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "Error",
  };
}
/* JavaCC - OriginalChecksum=b95cc8e44deb397ab00dbb8812a4853b (do not edit this line) */
